FROM maven:3.8.3-jdk-8 as builder

RUN mkdir /project

COPY settings.xml /usr/share/maven/conf/settings.xml

COPY ./UserPathBack/ /project/

WORKDIR /project/

RUN mvn clean package -Dmaven.test.skip=true

FROM registry.cn-beijing.aliyuncs.com/kdt/openjdk:17

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN echo 'Asia/Shanghai' >/etc/timezone

COPY --from=builder /project/target/userpath-0.0.1-SNAPSHOT.jar /userpath.jar

ENTRYPOINT [ "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "-Duser.timezone=GMT+08", "/userpath.jar"]

EXPOSE 8080