version: '3.8'
services: 
  saservice:
    build:
      dockerfile: Dockerfile-java
    image: saservice:v0
    container_name: saservice
    ports:
      - "33080:8080"
    volumes:
      - ./:/project/uploadPath
  

  sa_front_service:
    build:
      dockerfile: Dockerfile-nginx
    image: sa_front_service:v0
    container_name: sa_front_service
    depends_on:
      - saservice
    links:
      - saservice
    ports:
      - "13090:13090"